SELECT e.FIRST_NAME, e.LAST_NAME, e.DEPARTMENT_ID, d.DEPARTMENT_NAME FROM hr.Employees e
LEFT JOIN hr.Departments d  
ON e.DEPARTMENT_ID=d.DEPARTMENT_ID
WHERE d.DEPARTMENT_ID in (80,40);


SELECT FIRST_NAME, LAST_NAME, SALARY FROM hr.Employees 
WHERE SALARY >
(SELECT SALARY FROM hr.Employees
WHERE EMPLOYEE_ID = 182);


SELECT (e.FIRST_NAME || e.LAST_NAME) as FULLNAME, e.DEPARTMENT_ID, d.DEPARTMENT_NAME, e.MANAGER_ID FROM hr.Employees e
LEFT JOIN hr.Departments d
ON e.DEPARTMENT_ID=d.DEPARTMENT_ID;

 
SELECT (ep.FIRST_NAME || ep.LAST_NAME) AS ManagerName, d.DEPARTMENT_NAME FROM hr.Employees el
LEFT JOIN hr.Employees ep
ON el.MANAGER_ID=ep.EMPLOYEE_ID
LEFT JOIN hr.Departments d
ON el.DEPARTMENT_ID=d.DEPARTMENT_ID;

 
SELECT FIRST_NAME, LAST_NAME, DEPARTMENT_ID, 
CASE WHEN DEPARTMENT_ID=50 THEN 'Manager'
WHEN DEPARTMENT_ID=90 THEN 'SubManager'
ELSE 'Other'
END AS Profession FROM hr.Employees;